# Generated by Django 3.2.12 on 2022-04-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtStyle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('style', models.CharField(choices=[('PNT', 'Painting'), ('SCP', 'Sculpture'), ('PA', 'Pop_art'), ('SKH', 'Sketching'), ('CFT', 'Craft')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact_number', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rank', models.IntegerField()),
                ('art_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artstyle', to='Details.artstyle')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact_number', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('art_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_style', to='Details.artstyle')),
            ],
        ),
    ]
